### ISSUE TITLE
I made a thing from your thing

### ISSUE THREAD

**Issue by andybak** [antoinefournier/XParticle#1]
https://andybak.itch.io/xparticles-vr

Just thought you might like to know! I had no intention of doing something with particles. I wanted to do SDF ray-marching with compute shaders. But whilst looking for a simple example of a using a compute shader I found XParticle and realised that throwing a few million particles around with a random assortment of trig functions was much simpler and a lot more fun in the short-term.

I'll post my code at some point. Feel free to close this issue - I'm abusing issues as Github doesn't support any other way to message a dev.

**Comment by antoinefournier** [comment]
Hey nice good work :)
I'm happy if this helped you.
I saw this a while back but never responded.
